name: dms
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_otp: ^0.3.2
  rflutter_alert: ^1.0.3
  http: ^0.12.2
  dropdownfield: ^1.0.3
  syncfusion_flutter_pdf: ^18.2.45-beta
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.11
  url_launcher: ^5.5.0
  flutter_plugin_pdf_viewer: any
  flutter_pdfview: ^1.0.0+10
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
     - images/
  fonts:
  - family: Bangers
    fonts:
    - asset: fonts/Bangers-Regular.ttf
  - family: Questrial
    fonts:
    - asset: fonts/Questrial-Regular.ttf
